repositories = [
                "chef/chef", "chef/ohai", "chef/cheffish", "chef/chef-zero", "chef/chefstyle", "chef/welcome_bot", "chef/cookstyle", "chef/chef-dk", "chef/jump-in",
                "chef/win32-service", "chef/win32-eventlog", "chef/win32-taskscheduler", "chef/win32-process", "chef/win32-security",
                "chef/win32-file", "chef/win32-dir", "chef/win32-changejournal", "chef/win32-pipe", "chef/win32-sound", "chef/win32-file-security",
                "chef/win32-ipc", "chef/win32-clipboard", "chef/pr-win32ole", "chef/win32-file-stat", "chef/win32-shortcut", "chef/win32-certstore",
                "chef/win32-sapi", "chef/win32-ole", "chef/win32-mmap", "chef/win32-event", "chef/win32-nio", "chef/win32-changenotify", "chef/win32-file-attributes",
                "chef/win32-job", "chef/win32-mutex", "chef/win32-socket", "chef/win32-mailslot", "chef/ffi-win32-extensions", "chef/win32-semaphore",
                "chef/win32-dirmonitor", "chef/mixlib-cli", "chef/mixlib-log", "chef/mixlib-config", "chef/mixlib-authentication",
                "chef/mixlib-shellout", "chef/mixlib-versioning", "chef/mixlib-archive", "chef/knife-ec2", "chef/knife-rackspace", "chef/knife-openstack",
                "chef/knife-azure", "chef/knife-windows", "chef/knife-google", "chef/knife-linode", "chef/knife-push", "chef/knife-opc", "chef/knife-acl",
                "chef/knife-cloud", "chef/knife-reporting", "chef/knife-ec-backup", "chef/knife-kvm", "chef/knife-analytics", "chef/knife-ecs", "chef/knife-vcenter",
                "chef/knife-lpar", "chef/kitchen-appbundle-updater", "chef/kitchen-vcenter", "chef/chef-provisioning", "chef/chef-provisioning-aws",
                "chef/chef-provisioning-fog", "chef/chef-provisioning-ssh", "chef/chef-provisioning-central", "chef/chef-vault", "chef/chef-ruby-lvm",
                "chef/chef-ruby-lvm-attrib", "chef/ffi-libarchive", "chef/chocolatey-packages", "chef/homebrew-chef", "chef/ffi-yajl", "chef/libyajl2-gem",
                "chef/vagrant-omnibus", "chef/appbundler", "chef/rs-chef-api", "chef/omnibus", "chef/appbundle-updater", "chef/opscode-pushy-client",
                "chef/omnibus-software", "chef/chef-workstation", "chef/chef-apply", "chef/chef-manage", "chef/mixlib-install", "chef/mixlib-platform",
                "chef/opscode-pushy-server" ]

[[label]]
color = "e11d21"
mappings = [ "Bug", "bug", "Bug Fix" ]
name = "Type: Bug"

[[label]]
color = "c7def8"
name = "Type: Documentation"
mappings = ["Documentation", "documentation"]

[[label]]
color = "bfe5bf"
name = "Type: Jump In"
mappings = ["Easy", "hacktoberfest", "Hacktoberfest", "help wanted", "Help Wanted", "Jump In"]

[[label]]
color = "009800"
name = "Type: Enhancement"
mappings = ["Enhancement", "enhancement", "Improvement", "New Feature", "Feature", "Feature Request"]

[[label]]
color = "0052cc"
name = "Status: Duplicate"
mappings = [ "duplicate", "Duplicate" ]

[[label]]
color = "bfd4f2"
name = "Expeditor: Exclude From Changelog"
mappings = ["Changelog: Skip Update", "Exclude From Changelog"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip All"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Build"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Version Bump"
mappings = ["Version: Skip Bump"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Bump Minor Version"
mappings = ["Version: Bump Minor"]

[[label]]
color = "0052cc"
name = "Status: Finish for Merge"
mappings = ["Finish for Merge"]

[[label]]
color = "eb6420"
name = "Priority: Critical"
mappings = ["High Priority"]

[[label]]
color = "0052cc"
name = "Status: Incomplete"
mappings = ["Incomplete Contribution", "in progress"]

[[label]]
color = "eb6420"
name = "Priority: Low"
mappings = ["Low Priority"]

[[label]]
color = "eb6420"
name = "Priority: Medium"
mappings = ["Medium Priority"]

[[label]]
color = "e11d21"
name = "Type: Regression"
mappings = ["Regression"]

[[label]]
delete = true
name = "CLA Verified"

[[label]]
delete = true
name = "Signed CLA"

[[label]]
delete = true
name = "CLA Needed"

[[label]]
delete = true
name = "General"

[[label]]
delete = true
name = "office hours"

[[label]]
delete = true
name = "Help"

[[label]]
delete = true
name = "Delivery Change Created"

[[label]]
delete = true
name = "Status: Ready for Merge"

[[label]]
delete = true
name = "Status: Pending Maintainer Review"

[[label]]
delete = true
name = "Signed CLA"

[[label]]
name = "wontfix"
delete = true

[[label]]
name = "invalid"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Attack List"
delete = true

[[label]]
name = "Tech Cleanup"
delete = true

[[label]]
name = "Discussion"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Needs Action"
delete = true

[[label]]
color = "0052cc"
name = "Status: Won't Fix"
mappings = ["wontfix"]

[[label]]
color = "0052cc"
name = "Status: Confirmed"
mappings = ["Triaged"]

[[label]]
color = "0052cc"
name = "Status: Pending Contributor Response"
mappings = ["Waiting for Contributor Response", "Waiting", "Feedback Requested", "waitingresponse", "Waiting on Contributor"]

[[milestones]]
description = "Bucket to pull issues from for next minor. These issues should be fixable without needing a *major* version bump per semver; they're unlikely to cause a compatibility break or an API change."
name = "Accepted Minor"
state = "open"

[[milestones]]
description = "Bucket for breaking changes to pull for next Major"
name = "Accepted Major"
state = "open"

[[milestones]]
description = "Triaged issues that are low priority and are not being worked on."
name = "Help Wanted"
state = "open"

[[milestones]]
description = "Documentation updates and fixes"
name = "Documentation"
state = "open"

[[milestones]]
description = "Bucket for issues that are discussions or bikesheds and which are not yet directly actionable but also not yet closable, and are not appropriate to assign to either a major or minor release milestone.\r\n"
name = "Discussion"
state = "open"
