repositories = [ "example/fox", "example/wolf" ]

[[label]]
name = "bug"
color = "f29513"
mappings = [ "defect", "error" ]

[[label]]
name = "Jump In"
color = "123456"

[[milestone]]
name = "Accepted Major"
description = "Bucket for breaking changes to pull for next Major"
